# Makefile
using_cpp_template: using_cpp_template.o
	g++ using_cpp_template.o -o using_cpp_template
using_cpp_template.o: using_cpp_template.cpp
	g++ -c using_cpp_template.cpp
clean:
	rm -f using_cpp_template *.o
