# Makefile
IntSetListNoRecursion: IntSetListNoRecursion.o
	g++ IntSetListNoRecursion.o -o IntSetListNoRecursion
IntSetListNoRecursion.o: IntSetListNoRecursion.cpp
	g++ -c IntSetListNoRecursion.cpp
clean:
	rm -f IntSetListNoRecursion *.o
